spring:
  application:
    name: viaseguraapi
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.format_sql: true

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET:my-secret}
      expire-length: ${JWT_EXPIRE:3600000}

spring-doc:
  path-to-match:
    - /auth/**
    - /users/**
    - /h3_grid/**
    - /heatmap/**
    - /predictions/**
  swagger-ui:
    user-root-path: true