services:
  viaseguraapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viaseguraapi
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://viaseguradb:5432/viasegura
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=my-secret
      - JWT_EXPIRE=3600000
      - ORIGIN_PATTERNS=http://localhost:3000,http://localhost:8080,http://localhost:5173
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=America/Sao_Paulo
    depends_on:
      viaseguradb:
        condition: service_healthy
    networks:
      - viasegura-network
      - monitoring

  viaseguradb:
    image: postgres:16.3
    container_name: viaseguradb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=viasegura
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/data:/data
    networks:
      - viasegura-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "15432:80"
    depends_on:
      - viaseguradb
    networks:
      - viasegura-network

  data-loader:
    image: python:3.11-slim
    container_name: data-loader
    working_dir: /app
    volumes:
      - ./scripts:/app
    networks:
      - viasegura-network
    entrypoint: [ "/bin/bash", "/app/entrypoint.sh" ]
    depends_on:
      viaseguradb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  viasegura-network:
    driver: bridge
  monitoring:
    external: true
